### ISSUE TITLE
U Unsuccessful: 401 Your account has been temporarily blocked. Please contact our support team to get assistance.

### ISSUE THREAD

**Issue by RashmithaK** [pepesenaris/emails-from-create-react-app-example#1]
created MJ_APIKEY_PUBLIC=<api_key_public>
MJ_APIKEY_PRIVATE=<api_key_private>
 and replaced in code and verified its correct

getting below error
messageInfo { email: '******@gmail.com',
  fromEmail: 'info@ingsw.com',
  fromName: 'Star Wars',
  subject: 'Checkout this awesome droids' }
aaaa Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
(node:12788) UnhandledPromiseRejectionWarning: Error: Unsuccessful: 401 Your account has been temporarily blocked. Please contact our support team to get assistance.
    at C:\Users\RASHMITHA\Desktop\emails-from-create-react-app-example-master\node_modules\node-mailjet\mailjet-client.js:321:23
    at Request.callback (C:\Users\RASHMITHA\Desktop\emails-from-create-react-app-example-master\node_modules\superagent\lib\node\index.js:728:3)
    at parser (C:\Users\RASHMITHA\Desktop\emails-from-create-react-app-example-master\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\RASHMITHA\Desktop\emails-from-create-react-app-example-master\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:12788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by scriptwithahmad** [comment]
I'm also searching how to resolve this error.
If you find out the solution then also guide me here.
